/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FarmingPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "SECONDS_PER_YEAR"
      | "calculateRewards"
      | "claimRewards"
      | "completeHarvest"
      | "createPool"
      | "emergencyUnstake"
      | "getPoolInfo"
      | "getPoolInvestors"
      | "getTotalPools"
      | "getUserPools"
      | "getUserStake"
      | "guiToken"
      | "owner"
      | "pause"
      | "paused"
      | "poolCount"
      | "poolExists"
      | "poolInvestors"
      | "pools"
      | "renounceOwnership"
      | "setPoolStatus"
      | "stake"
      | "stakes"
      | "transferOwnership"
      | "unpause"
      | "unstake"
      | "userPools"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyWithdrawal"
      | "HarvestCompleted"
      | "OwnershipTransferred"
      | "Paused"
      | "PoolCreated"
      | "PoolStatusChanged"
      | "RewardsPaid"
      | "Staked"
      | "Unpaused"
      | "Unstaked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SECONDS_PER_YEAR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateRewards",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeHarvest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPool",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyUnstake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolInvestors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPools",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPools",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStake",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "guiToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "poolCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "poolInvestors",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pools", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPoolStatus",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakes",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userPools",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SECONDS_PER_YEAR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeHarvest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyUnstake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolInvestors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "guiToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolExists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolInvestors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPoolStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userPools", data: BytesLike): Result;
}

export namespace EmergencyWithdrawalEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HarvestCompletedEvent {
  export type InputTuple = [poolId: BigNumberish, totalYield: BigNumberish];
  export type OutputTuple = [poolId: bigint, totalYield: bigint];
  export interface OutputObject {
    poolId: bigint;
    totalYield: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolCreatedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    fieldId: string,
    cropName: string
  ];
  export type OutputTuple = [poolId: bigint, fieldId: string, cropName: string];
  export interface OutputObject {
    poolId: bigint;
    fieldId: string;
    cropName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolStatusChangedEvent {
  export type InputTuple = [poolId: BigNumberish, isActive: boolean];
  export type OutputTuple = [poolId: bigint, isActive: boolean];
  export interface OutputObject {
    poolId: bigint;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsPaidEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [poolId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    poolId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [poolId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    poolId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [poolId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    poolId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FarmingPool extends BaseContract {
  connect(runner?: ContractRunner | null): FarmingPool;
  waitForDeployment(): Promise<this>;

  interface: FarmingPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  SECONDS_PER_YEAR: TypedContractMethod<[], [bigint], "view">;

  calculateRewards: TypedContractMethod<
    [poolId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  claimRewards: TypedContractMethod<
    [poolId: BigNumberish],
    [void],
    "nonpayable"
  >;

  completeHarvest: TypedContractMethod<
    [poolId: BigNumberish, actualYield: BigNumberish],
    [void],
    "nonpayable"
  >;

  createPool: TypedContractMethod<
    [
      _fieldId: string,
      _cropName: string,
      _minStake: BigNumberish,
      _maxStake: BigNumberish,
      _rewardRate: BigNumberish,
      _lockDuration: BigNumberish,
      _harvestTime: BigNumberish,
      _riskLevel: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  emergencyUnstake: TypedContractMethod<
    [poolId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getPoolInfo: TypedContractMethod<
    [poolId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        fieldId: string;
        cropName: string;
        minStake: bigint;
        maxStake: bigint;
        totalStaked: bigint;
        rewardRate: bigint;
        lockDuration: bigint;
        harvestTime: bigint;
        isActive: boolean;
        riskLevel: bigint;
        investorsCount: bigint;
      }
    ],
    "view"
  >;

  getPoolInvestors: TypedContractMethod<
    [poolId: BigNumberish],
    [string[]],
    "view"
  >;

  getTotalPools: TypedContractMethod<[], [bigint], "view">;

  getUserPools: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  getUserStake: TypedContractMethod<
    [poolId: BigNumberish, user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint] & {
        amount: bigint;
        timestamp: bigint;
        unlockTime: bigint;
        rewardsPaid: bigint;
        isActive: boolean;
        pendingRewards: bigint;
      }
    ],
    "view"
  >;

  guiToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  poolCount: TypedContractMethod<[], [bigint], "view">;

  poolExists: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  poolInvestors: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  pools: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        fieldId: string;
        cropName: string;
        minStake: bigint;
        maxStake: bigint;
        totalStaked: bigint;
        rewardRate: bigint;
        lockDuration: bigint;
        harvestTime: bigint;
        isActive: boolean;
        riskLevel: bigint;
        totalRewards: bigint;
        investorsCount: bigint;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPoolStatus: TypedContractMethod<
    [poolId: BigNumberish, _isActive: boolean],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<
    [poolId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakes: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        amount: bigint;
        timestamp: bigint;
        unlockTime: bigint;
        rewardsPaid: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  unstake: TypedContractMethod<[poolId: BigNumberish], [void], "nonpayable">;

  userPools: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SECONDS_PER_YEAR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateRewards"
  ): TypedContractMethod<
    [poolId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[poolId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeHarvest"
  ): TypedContractMethod<
    [poolId: BigNumberish, actualYield: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createPool"
  ): TypedContractMethod<
    [
      _fieldId: string,
      _cropName: string,
      _minStake: BigNumberish,
      _maxStake: BigNumberish,
      _rewardRate: BigNumberish,
      _lockDuration: BigNumberish,
      _harvestTime: BigNumberish,
      _riskLevel: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyUnstake"
  ): TypedContractMethod<[poolId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPoolInfo"
  ): TypedContractMethod<
    [poolId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        fieldId: string;
        cropName: string;
        minStake: bigint;
        maxStake: bigint;
        totalStaked: bigint;
        rewardRate: bigint;
        lockDuration: bigint;
        harvestTime: bigint;
        isActive: boolean;
        riskLevel: bigint;
        investorsCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolInvestors"
  ): TypedContractMethod<[poolId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTotalPools"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserPools"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserStake"
  ): TypedContractMethod<
    [poolId: BigNumberish, user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint] & {
        amount: bigint;
        timestamp: bigint;
        unlockTime: bigint;
        rewardsPaid: bigint;
        isActive: boolean;
        pendingRewards: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "guiToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "poolCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "poolExists"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "poolInvestors"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "pools"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        fieldId: string;
        cropName: string;
        minStake: bigint;
        maxStake: bigint;
        totalStaked: bigint;
        rewardRate: bigint;
        lockDuration: bigint;
        harvestTime: bigint;
        isActive: boolean;
        riskLevel: bigint;
        totalRewards: bigint;
        investorsCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPoolStatus"
  ): TypedContractMethod<
    [poolId: BigNumberish, _isActive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<
    [poolId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        amount: bigint;
        timestamp: bigint;
        unlockTime: bigint;
        rewardsPaid: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[poolId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userPools"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "EmergencyWithdrawal"
  ): TypedContractEvent<
    EmergencyWithdrawalEvent.InputTuple,
    EmergencyWithdrawalEvent.OutputTuple,
    EmergencyWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "HarvestCompleted"
  ): TypedContractEvent<
    HarvestCompletedEvent.InputTuple,
    HarvestCompletedEvent.OutputTuple,
    HarvestCompletedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PoolCreated"
  ): TypedContractEvent<
    PoolCreatedEvent.InputTuple,
    PoolCreatedEvent.OutputTuple,
    PoolCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PoolStatusChanged"
  ): TypedContractEvent<
    PoolStatusChangedEvent.InputTuple,
    PoolStatusChangedEvent.OutputTuple,
    PoolStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsPaid"
  ): TypedContractEvent<
    RewardsPaidEvent.InputTuple,
    RewardsPaidEvent.OutputTuple,
    RewardsPaidEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Unstaked"
  ): TypedContractEvent<
    UnstakedEvent.InputTuple,
    UnstakedEvent.OutputTuple,
    UnstakedEvent.OutputObject
  >;

  filters: {
    "EmergencyWithdrawal(address,uint256)": TypedContractEvent<
      EmergencyWithdrawalEvent.InputTuple,
      EmergencyWithdrawalEvent.OutputTuple,
      EmergencyWithdrawalEvent.OutputObject
    >;
    EmergencyWithdrawal: TypedContractEvent<
      EmergencyWithdrawalEvent.InputTuple,
      EmergencyWithdrawalEvent.OutputTuple,
      EmergencyWithdrawalEvent.OutputObject
    >;

    "HarvestCompleted(uint256,uint256)": TypedContractEvent<
      HarvestCompletedEvent.InputTuple,
      HarvestCompletedEvent.OutputTuple,
      HarvestCompletedEvent.OutputObject
    >;
    HarvestCompleted: TypedContractEvent<
      HarvestCompletedEvent.InputTuple,
      HarvestCompletedEvent.OutputTuple,
      HarvestCompletedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PoolCreated(uint256,string,string)": TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;
    PoolCreated: TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;

    "PoolStatusChanged(uint256,bool)": TypedContractEvent<
      PoolStatusChangedEvent.InputTuple,
      PoolStatusChangedEvent.OutputTuple,
      PoolStatusChangedEvent.OutputObject
    >;
    PoolStatusChanged: TypedContractEvent<
      PoolStatusChangedEvent.InputTuple,
      PoolStatusChangedEvent.OutputTuple,
      PoolStatusChangedEvent.OutputObject
    >;

    "RewardsPaid(uint256,address,uint256)": TypedContractEvent<
      RewardsPaidEvent.InputTuple,
      RewardsPaidEvent.OutputTuple,
      RewardsPaidEvent.OutputObject
    >;
    RewardsPaid: TypedContractEvent<
      RewardsPaidEvent.InputTuple,
      RewardsPaidEvent.OutputTuple,
      RewardsPaidEvent.OutputObject
    >;

    "Staked(uint256,address,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Unstaked(uint256,address,uint256)": TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
    Unstaked: TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
  };
}
